language: python
python:
    - "3.6"

sudo: false
cache: pip

before_install: cd sphinx


install: "pip install sphinx"
install: "pip install sphinx_rtd_theme"
// script: sphinx-build -nWT -b html . _build/html
script: ls -la && pwd