language: python
python:
    - "3.6"

sudo: false
cache: pip

install: "pip install sphinx"
install: "pip install sphinx_rtd_theme"
before_script: cd /sphinx/
script: sphinx-build -nWT -b html -d _build/doctrees  . _build/html